export const genre = [
	"Action",
	"Adventure",
	"Comedy",
	"Drama",
	"Slice of Life",
	"Fantasy",
	"Magic",
	"Supernatural",
	"Horror",
	"Mystery",
	"Psychological",
	"Romance",
	"Sci-Fi",
	"Game",
	"Ecchi",
	"Demons",
	"Harem",
	"Josei",
	"Martial Arts",
	"Historical",
	"Military",
	"Mecha",
	"Music",
	"Parody",
	"Police",
	"Reverse Harem",
	"School",
	"Seinen",
	"Shoujo",
	"Shoujo-ai",
	"Shounen",
	"Shounen-ai",
	"Space",
	"Sports",
	"Super Power",
].sort();
export const studio = [
	"	A-1 Pictures",
	"AIC",
	"Ajia-Do",
	"Bibury Animation Studios",
	"Bones",
	"Brain's Base",
	"C2C",
	"CloverWorks",
	"Doga Kobo",
	"EMT Squared",
	"feel.",
	"Gainax",
	"Gonzo",
	"Hoods Entertainment",
	"J.C.Staff",
	"Kinema Citrus",
	"Kyoto Animation",
	"Lay-duce",
	"Lerche",
	"LIDENFILMS",
	"Maho Film",
	"MAPPA",
	"Nut",
	"OLM",
	"P.A. Works",
	"Pine Jam",
	"Production I.G",
	"Project No.9",
	"SANZIGEN",
	"Satelight",
	"Seven Arcs",
	"Shaft",
	"Shin-Ei Animation",
	"Silver Link.",
	"Studio Pierrot",
	"Sunrise",
	"Tatsunoko Production",
	"Telecom Animation Film",
	"TMS Entertainment",
	"TNK",
	"Toei Animation",
].sort();
export const sidebarLinks = [
	{
		name: "Home",
		pathName: "home",
		icon: "fal fa-home",
	},
	{ divider: "Anime" },
	{
		name: "List Anime",
		icon: "fal fa-list",
		group: [
			{
				name: "Anime BD",
				pathName: "anime.animebd",
				icon: "fal fa-book",
			},
			{
				name: "Movie List",
				pathName: "anime.animebd",
				icon: "fal fa-book",
			},
			{
				name: "Anime OVA",
				pathName: "anime.animebd",
				icon: "fal fa-book",
			},
			{
				name: "Anime ONA",
				pathName: "anime.animebd",
				icon: "fal fa-book",
			},
		],
	},
	{
		name: "Musim Anime",
		icon: "fal fa-sun",
		group: [
			{
				name: "Winter",
				pathName: "season.winter",
				icon: "fal fa-snowflake",
			},
			{
				name: "Spring",
				pathName: "season.spring",
				icon: "fal fa-flower",
			},
			{
				name: "Summer",
				pathName: "season.summer",
				icon: "fal fa-sun",
			},
			{
				name: "Fall",
				pathName: "season.fall",
				icon: "fal fa-leaf-maple",
			},
		],
	},
	{
		name: "Jadwal Anime",
		pathName: "jadwal",
		icon: "fal fa-calendar-alt",
	},
];
export const jadwalAnime = [
	{
		senin: "Shingeki no Kyojin 5",
		selasa: "Black Clover",
		rabu: "Gekidol",
		kamis: "Dr Stone 3",
		jumat: "Gotoubun no Hanayome 2",
		sabtu: "Jujutsu Kaisen",
		minggu: "Boruto",
	},
	{
		senin: "Kemeno Jihen",
		selasa: "Uma Musume: Pretty Derby Season 2",
		rabu: "Log Horizon Season 3",
		kamis: "Beastars Season 2",
		jumat: "2.43: Seiin Koukou Danshi Volley-bu",
		sabtu: "Back Arrow",
		minggu: "World Trigger 2",
	},
	{
		senin: "Non Non Biyori Season 3",
		rabu: "Nanatsu no Taizai Season 4",
		kamis: "Hataraku Saibou Season 2",
		jumat: "Higurashi no Naku Koro ni (2020)",
		sabtu: "Hataraku Saibou Black (TV)",
		minggu: "Dragon Quest",
	},
	{
		senin: "Idoly Pride",
		rabu: "Tensei shitara Slime Datta Ken Season 2",
		kamis: "Hortensia Saga",
		jumat: "Jaku - Chara Tomozaki - kun",
		sabtu: "King's Raid: Ishi wo Tsugumono-tachi",
		minggu: "Horimiya",
	},
	{
		senin: "Lasdan",
		rabu: "Wonder Egg Priority",
		kamis: "Kaifuku Jutsushi no Yarinaoshi",
		jumat: "Kumo Desu ga, Nani ka ?",
		sabtu: "Ore dake Haireru Kakushi Dungeon",
	},
	{
		senin: "SK Eight",
		kamis: "Re:Zero kara Hajimeru Isekai Seikatsu Season 2",
	},
	{
		senin: "Mushoku Tensei: Isekai Ittara Honki Dasu",
		kamis: "Soukou Musume Senki",
	},
	{
		senin: "Urasekai Picnic",
		kamis: "Yakusoku no Neverland Season 2",
	},
	{
		kamis: "Yuru Camp△ Season 2",
	},
];
